#!/bin/sh

if [ "$(whoami)" != "root" ]; then
	SUDO=sudo
fi

# Add Docker's official GPG key:
$SUDO apt-get update && \
$SUDO apt-get install ca-certificates curl gnupg && \
$SUDO install -m 0755 -d /etc/apt/keyrings && \
curl -fsSL https://download.docker.com/linux/debian/gpg | $SUDO gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
$SUDO chmod a+r /etc/apt/keyrings/docker.gpg && \

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  $SUDO tee /etc/apt/sources.list.d/docker.list > /dev/null

$SUDO apt-get update
$SUDO apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
